Add quotes around variable.

diff --git a/tasks/general/acct_mgmt/users.yml b/tasks/general/acct_mgmt/users.yml
--- a/tasks/general/acct_mgmt/users.yml
+++ b/tasks/general/acct_mgmt/users.yml
@@ -303,7 +303,7 @@
         # Ensure the container exists. Should be found even if stopped.
         exists=`docker ps | grep -c $container`
         if [[ $exists != "1" ]]; then
-          echo "ERROR: Container $container was not found." >&2
+          echo "ERROR: Container '$container' was not found." >&2
           echo "Please choose from the available list:"
           docker ps
           return;
